### ISSUE TITLE
TESForm::LoadForm and formIDs

### ISSUE THREAD

**Issue by shadeMe** [DavidJCobb/tesv-cobb-api#1]
Sorry, this seems to be the only way to add a comment to a line outside of a commit/pull request.

https://github.com/DavidJCobb/tesv-cobb-api/blob/46ad4eafa32bfd686b018fa3c60aefb6a606c5a0/SKSE%20Plugin/CobbAPI/Services/CellInteriorDataService.cpp#L48

FormIds stored in pointer fields during the TESForm::LoadForm() phase are resolved in the TESForm::InitItem() phase (referred to as TESForm::Link() in the xSE source). The member function is usually a couple of offsets below LoadForm(). At least, that's how it used to be in Oblivion.

**Comment by DavidJCobb** [comment]
Thanks for the information. I'll update the comment in my code, and that information should make it in next time I upload an update.
